# Generated by Django 5.2.6 on 2025-12-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_guest_email_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='main.room')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
